// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/category/category.proto

package category

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Categories service

func NewCategoriesEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Categories service

type CategoriesService interface {
	GetCategoriesPage(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	SaveCategory(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	UpdateGoodsCategory(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	GetGoodsCategoryById(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	DeleteBatch(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	GetCategoriesForSearch(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	SelectByLevelAndParentIdsAndNumber(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type categoriesService struct {
	c    client.Client
	name string
}

func NewCategoriesService(name string, c client.Client) CategoriesService {
	return &categoriesService{
		c:    c,
		name: name,
	}
}

func (c *categoriesService) GetCategoriesPage(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Categories.GetCategoriesPage", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *categoriesService) SaveCategory(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Categories.SaveCategory", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *categoriesService) UpdateGoodsCategory(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Categories.UpdateGoodsCategory", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *categoriesService) GetGoodsCategoryById(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Categories.GetGoodsCategoryById", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *categoriesService) DeleteBatch(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Categories.DeleteBatch", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *categoriesService) GetCategoriesForSearch(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Categories.GetCategoriesForSearch", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *categoriesService) SelectByLevelAndParentIdsAndNumber(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Categories.SelectByLevelAndParentIdsAndNumber", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Categories service

type CategoriesHandler interface {
	GetCategoriesPage(context.Context, *Request, *Response) error
	SaveCategory(context.Context, *Request, *Response) error
	UpdateGoodsCategory(context.Context, *Request, *Response) error
	GetGoodsCategoryById(context.Context, *Request, *Response) error
	DeleteBatch(context.Context, *Request, *Response) error
	GetCategoriesForSearch(context.Context, *Request, *Response) error
	SelectByLevelAndParentIdsAndNumber(context.Context, *Request, *Response) error
}

func RegisterCategoriesHandler(s server.Server, hdlr CategoriesHandler, opts ...server.HandlerOption) error {
	type categories interface {
		GetCategoriesPage(ctx context.Context, in *Request, out *Response) error
		SaveCategory(ctx context.Context, in *Request, out *Response) error
		UpdateGoodsCategory(ctx context.Context, in *Request, out *Response) error
		GetGoodsCategoryById(ctx context.Context, in *Request, out *Response) error
		DeleteBatch(ctx context.Context, in *Request, out *Response) error
		GetCategoriesForSearch(ctx context.Context, in *Request, out *Response) error
		SelectByLevelAndParentIdsAndNumber(ctx context.Context, in *Request, out *Response) error
	}
	type Categories struct {
		categories
	}
	h := &categoriesHandler{hdlr}
	return s.Handle(s.NewHandler(&Categories{h}, opts...))
}

type categoriesHandler struct {
	CategoriesHandler
}

func (h *categoriesHandler) GetCategoriesPage(ctx context.Context, in *Request, out *Response) error {
	return h.CategoriesHandler.GetCategoriesPage(ctx, in, out)
}

func (h *categoriesHandler) SaveCategory(ctx context.Context, in *Request, out *Response) error {
	return h.CategoriesHandler.SaveCategory(ctx, in, out)
}

func (h *categoriesHandler) UpdateGoodsCategory(ctx context.Context, in *Request, out *Response) error {
	return h.CategoriesHandler.UpdateGoodsCategory(ctx, in, out)
}

func (h *categoriesHandler) GetGoodsCategoryById(ctx context.Context, in *Request, out *Response) error {
	return h.CategoriesHandler.GetGoodsCategoryById(ctx, in, out)
}

func (h *categoriesHandler) DeleteBatch(ctx context.Context, in *Request, out *Response) error {
	return h.CategoriesHandler.DeleteBatch(ctx, in, out)
}

func (h *categoriesHandler) GetCategoriesForSearch(ctx context.Context, in *Request, out *Response) error {
	return h.CategoriesHandler.GetCategoriesForSearch(ctx, in, out)
}

func (h *categoriesHandler) SelectByLevelAndParentIdsAndNumber(ctx context.Context, in *Request, out *Response) error {
	return h.CategoriesHandler.SelectByLevelAndParentIdsAndNumber(ctx, in, out)
}
